image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "webide"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'

default:
  artifacts:
    expire_in: 72 hours 
    paths:
      - .local/detector
      - .local/lib
      - .local/bin
      - .local/include
      - .local/share
      - results
      - config
      - images/
      - doc/
      - juggler.env
    reports:
      dotenv: juggler.env

stages:
  - config
  - build
  - docs
  - test 
  - finalize 
  - deploy

common:setup:
  stage: config
  script:
    - git clone https://eicweb.phy.anl.gov/EIC/benchmarks/common_bench.git setup 
    - source setup/bin/env.sh && ./setup/bin/install_common.sh

common:detector:
  stage: build
  needs: ["common:setup"]
  script:
    - |
      export BEAMLINE_CONFIG="ip6"
      if [[ -z "${JUGGLER_DETECTOR}" ]]; then 
        export JUGGLER_DETECTOR="reference_detector"
      fi
    - |
      if [[ "x${CI_PIPELINE_SOURCE}" == "xmerge_request_event"  || "$CI_COMMIT_BRANCH" == "master" ]]; then
        export BEAMLINE_CONFIG_VERSION=${CI_COMMIT_REF_NAME}
        echo "BEAMLINE_CONFIG          = ${BEAMLINE_CONFIG}"
        echo "BEAMLINE_CONFIG_VERSION  = ${CI_COMMIT_REF_NAME}"
        echo "JUGGLER_DETECTOR         = ${JUGGLER_DETECTOR}"
        # add to env file testing
        echo "BEAMLINE_CONFIG_VERSION=$CI_COMMIT_REF_NAME" >> juggler.env
        echo "BEAMLINE_CONFIG=$BEAMLINE_CONFIG" >> juggler.env
        echo "JUGGLER_DETECTOR=$JUGGLER_DETECTOR" >> juggler.env
        # if specific juggler version is requested
        if [[ -n "${JUGGLER_DETECTOR_VERSION}" ]]; then
          echo "JUGGLER_DETECTOR_VERSION = ${CI_COMMIT_REF_NAME}"
          echo "JUGGLER_DETECTOR_VERSION=$CI_COMMIT_REF_NAME" >> juggler.env
        fi
      fi
    - source .local/bin/env.sh
    - mkdir -p build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=${LOCAL_PREFIX} && make -j20 && make install  && cd ..
    - mkdir_local_data_link sim_output
    - ls -lrth
    - print_env.sh

overlap_check:
  stage: test
  needs: 
    - ["common:detector"]
  script:
    - |
      set -o allexport
      source juggler.env
      set +o allexport
    - source .local/bin/env.sh
    - mkdir doc
    - ls -lrth
    - checkOverlaps -c eic_ip6.xml 


detectors:reference_detector:
  stage: deploy
  needs: ["overlap_check"]
  variables:
    JUGGLER_DETECTOR: "$JUGGLER_DETECTOR"
    JUGGLER_DETECTOR_VERSION: "$JUGGLER_DETECTOR_VERSION"
    BEAMLINE_CONFIG: "$BEAMLINE_CONFIG"
    BEAMLINE_CONFIG_VERSION: "$BEAMLINE_CONFIG_VERSION"
  trigger:
    project: EIC/detectors/reference_detector
    strategy: depend
